### ISSUE TITLE
UI getting stuck after transaction

### ISSUE THREAD

**Issue by LividDS** [Renewed-Scripts/Renewed-Banking#45]
SCRIPT ERROR: @Renewed-Banking/server/main.lua:123: invalid UTF-8 code
script:renewed-banking:nui Uncaught (in promise) TypeError: Cannot read properties of null (reading '0') (@renewed-banking/web/public/build/bundle.js:1)

These are the two errors we get.

**Comment by uShifty** [comment]
This error should be fixed, Try updating to the latest release posted!

**Comment by jaylac2000** [comment]
and make sure not to rename the resource

**Comment by mikeyxb** [comment]
I still get this issue every now and then, the money also gets lost during the UI sticking, im on version 2.0.2

**Comment by Medit8z** [comment]
I am also getting this issue with a different error. Uncaught (in promise) TypeError: Cannot read properties of null (reading '0') (@renewed-banking/web/public/build/bundle.js.1

When we restart server cache and load the server people that go to deposit or withdraw money get the UI stuck on their screen and what ever they tried to deposit/withdraw poofs and they have to F8 quit and rejoin in order to use the bank.

Any help would be very appreciated.

**Comment by Jaaaat** [comment]
> I am also getting this issue with a different error. Uncaught (in promise) TypeError: Cannot read properties of null (reading '0') (@renewed-banking/web/public/build/bundle.js.1
> 
> When we restart server cache and load the server people that go to deposit or withdraw money get the UI stuck on their screen and what ever they tried to deposit/withdraw poofs and they have to F8 quit and rejoin in order to use the bank.
> 
> Any help would be very appreciated.

Im still getting this issue... any fixes?
